### ISSUE TITLE
Can't hold audio call?

### ISSUE THREAD

**Issue by frankenten13** [xcy396/EasyLinphone#4]
Drear xcy396, simple library, but i can't see direct method hold call and continues call. 
Now i use 
`mCall = EasyLinphone.getLC().getCurrentCall();`
to hold
`LinphoneManager.getLc().pauseCall(mCall);`
and continues 
`LinphoneManager.getLc().resumeCall(mCall);`
I thinks direct method is helpful than this.
Can you support that? Thanks

**Comment by xcy396** [comment]
Thanks for your support, I will add these methods and fix the bugs in the next version. Coming soon!
